/**
* @file Source code generated by PDL compiler.
* @version 1.0
* @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
* @schemaversion 1.0.0.2
*/
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../QuickStart/ViewModels/QuickStartPartViewModel" />
define(["require", "exports", "../../QuickStart/ViewModels/QuickStartPartViewModel"], function (require, exports) {
    "use strict";
    var Main;
    (function (Main) {
        "use strict";
        Main.part = {
            "name": "QuickStartPart",
            "viewModel": "QuickStart$QuickStartPartViewModel",
            "partKind": 21,
            "canUseOldInputVersions": false,
            "inputs": [],
            "bindings": [],
            "details": [
                {
                    "blade": "QuickStartBlade"
                }
            ]
        };
    })(Main || (Main = {}));
    return Main;
});
