/**
* @file Source code generated by PDL compiler.
* @version 1.0
* @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
* @schemaversion 1.0.0.2
*/
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Browse/ViewModels/ResourcePartViewModel" />
define(["require", "exports", "../../Browse/ViewModels/ResourcePartViewModel"], function (require, exports) {
    "use strict";
    var Main;
    (function (Main) {
        "use strict";
        Main.part = {
            "name": "ResourcePart",
            "viewModel": "Browse$ResourcePartViewModel",
            "partKind": 22,
            "canUseOldInputVersions": false,
            "inputs": [
                "id"
            ],
            "bindings": [
                {
                    "property": "id",
                    "valuesFrom": [
                        {
                            "referenceType": 1,
                            "property": "id"
                        }
                    ]
                }
            ],
            "details": [
                {
                    "blade": "ResourceBlade",
                    "selectableBindings": [
                        {
                            "property": "id",
                            "valuesFrom": [
                                {
                                    "referenceType": 0,
                                    "property": "content.assetId"
                                }
                            ]
                        }
                    ]
                }
            ],
            "assetType": "MyResource",
            "assetIdInputProperty": "id"
        };
    })(Main || (Main = {}));
    return Main;
});
