/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../TypeReferences.d.ts" />
/// <amd-bundling root="true" />

import FxComposition = require ("Fx/Composition");
import FxSelectable2 = require ("Fx/Composition/Selectable");
export = BladeDefinitions;
module BladeDefinitions {
    var extensionName: string = "JWTestExtension";
    function createOptions<TParameters, TOutputs>(onClosed: FxComposition.BladeClosedWithDataHandler<any>, parameters?: TParameters, callbacks?: FxSelectable2.PdlBladeCallbacks<TOutputs>): FxSelectable2.PdlBladeReferenceOptions<TParameters, TOutputs> {
        return {
                onClosed: onClosed,
                parameters: parameters,
                callbacks: callbacks
            };
    }
    export interface PropertiesBladeInputs {
        id: any;
    }
    export class PropertiesBladeReference extends FxSelectable2.PdlBladeReference<PropertiesBladeInputs, void> {
        public constructor(parameters: PropertiesBladeInputs, onClosed?: FxComposition.BladeClosedWithDataHandler<any>) {
            super("PropertiesBlade", extensionName, createOptions<PropertiesBladeInputs, void>(onClosed, parameters), {
                    });
        }
    }
    export interface ResourceBladeInputs {
        id: any;
    }
    export class ResourceBladeReference extends FxSelectable2.PdlBladeReference<ResourceBladeInputs, void> {
        public constructor(parameters: ResourceBladeInputs, onClosed?: FxComposition.BladeClosedWithDataHandler<any>) {
            super("ResourceBlade", extensionName, createOptions<ResourceBladeInputs, void>(onClosed, parameters), {
                    });
        }
    }
    export class QuickStartBladeReference extends FxSelectable2.PdlBladeReference<void, void> {
        public constructor(onClosed?: FxComposition.BladeClosedWithDataHandler<any>) {
            super("QuickStartBlade", extensionName, createOptions<void, void>(onClosed, undefined), {
                    });
        }
    }
    export class CreateBladeReference<TResult, TConfig> extends FxSelectable2.ParameterProviderBladeReference<void, TResult, TConfig> {
        public constructor(options: FxSelectable2.ParameterProviderOptions<void, TResult, TConfig>) {
            super("CreateBlade", extensionName, options);
        }
    }
}
