/**
* @file Source code generated by PDL compiler.
* @version 1.0
* @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
* @schemaversion 1.0.0.2
*/
/// <reference path="../TypeReferences.d.ts" />
/// <amd-bundling root="true" />
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
define(["require", "exports", "Fx/Composition/Selectable"], function (require, exports, FxSelectable2) {
    "use strict";
    var BladeDefinitions;
    (function (BladeDefinitions) {
        var extensionName = "JWTestExtension";
        function createOptions(onClosed, parameters, callbacks) {
            return {
                onClosed: onClosed,
                parameters: parameters,
                callbacks: callbacks
            };
        }
        var PropertiesBladeReference = (function (_super) {
            __extends(PropertiesBladeReference, _super);
            function PropertiesBladeReference(parameters, onClosed) {
                _super.call(this, "PropertiesBlade", extensionName, createOptions(onClosed, parameters), {});
            }
            return PropertiesBladeReference;
        }(FxSelectable2.PdlBladeReference));
        BladeDefinitions.PropertiesBladeReference = PropertiesBladeReference;
        var ResourceBladeReference = (function (_super) {
            __extends(ResourceBladeReference, _super);
            function ResourceBladeReference(parameters, onClosed) {
                _super.call(this, "ResourceBlade", extensionName, createOptions(onClosed, parameters), {});
            }
            return ResourceBladeReference;
        }(FxSelectable2.PdlBladeReference));
        BladeDefinitions.ResourceBladeReference = ResourceBladeReference;
        var QuickStartBladeReference = (function (_super) {
            __extends(QuickStartBladeReference, _super);
            function QuickStartBladeReference(onClosed) {
                _super.call(this, "QuickStartBlade", extensionName, createOptions(onClosed, undefined), {});
            }
            return QuickStartBladeReference;
        }(FxSelectable2.PdlBladeReference));
        BladeDefinitions.QuickStartBladeReference = QuickStartBladeReference;
        var CreateBladeReference = (function (_super) {
            __extends(CreateBladeReference, _super);
            function CreateBladeReference(options) {
                _super.call(this, "CreateBlade", extensionName, options);
            }
            return CreateBladeReference;
        }(FxSelectable2.ParameterProviderBladeReference));
        BladeDefinitions.CreateBladeReference = CreateBladeReference;
    })(BladeDefinitions || (BladeDefinitions = {}));
    return BladeDefinitions;
});
