/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../TypeReferences.d.ts" />

import Icons = require ("../Shared/Icons");
import ClientResources = require ("ClientResources");
import EntryPointModule = require ("Program");
export = ExtensionDefinition;
module ExtensionDefinition {
    "use strict";
    var untypedManifest: any = {
  "name": null,
  "version": null,
  "schemaVersion": null,
  "sdkVersion": null,
  "notifications": [],
  "assetTypes": [],
  "notifications2": [],
  "startBoardParts": [],
  "blades": [],
  "galleryParts": [],
  "redirects": []
};
    untypedManifest.pageVersion = window.fx.environment.pageVersion;
    export var manifest: MsPortalFx.Extension.Manifest = untypedManifest;
    MsPortalFx.Extension.registerAmd<typeof EntryPointModule>(manifest, "Program", require, "../_generated/Blades/", "../_generated/Parts", "../_generated/Controls");
}
