//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JWTestExtensionResourceProvider.RequestHandlers
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OperationResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$saferootprojectname$ResourceProvider.RequestHandlers.OperationResources", typeof(OperationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deletes Nested resources..
        /// </summary>
        internal static string NestedResourceTypeDeleteOperationDescription
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeDeleteOperationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Nested Resource.
        /// </summary>
        internal static string NestedResourceTypeDeleteOperationDisplayName
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeDeleteOperationDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The nested resource type..
        /// </summary>
        internal static string NestedResourceTypeDescription
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nested Resource Type.
        /// </summary>
        internal static string NestedResourceTypeDisplayName
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reads Nested resources..
        /// </summary>
        internal static string NestedResourceTypeReadOperationDescription
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeReadOperationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read Nested Resource.
        /// </summary>
        internal static string NestedResourceTypeReadOperationDisplayName
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeReadOperationDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Writes Nested resources..
        /// </summary>
        internal static string NestedResourceTypeWriteOperationDescription
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeWriteOperationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write Nested Resource.
        /// </summary>
        internal static string NestedResourceTypeWriteOperationDisplayName
        {
            get
            {
                return ResourceManager.GetString("NestedResourceTypeWriteOperationDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sample Resource Provider.
        /// </summary>
        internal static string ResourceProviderDisplayName
        {
            get
            {
                return ResourceManager.GetString("ResourceProviderDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deletes Root resources..
        /// </summary>
        internal static string RootResourceTypeDeleteOperationDescription
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeDeleteOperationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Root Resource.
        /// </summary>
        internal static string RootResourceTypeDeleteOperationDisplayName
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeDeleteOperationDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The root resource type..
        /// </summary>
        internal static string RootResourceTypeDescription
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Root Resource Type.
        /// </summary>
        internal static string RootResourceTypeDisplayName
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reads Root resources..
        /// </summary>
        internal static string RootResourceTypeReadOperationDescription
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeReadOperationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read Root Resource.
        /// </summary>
        internal static string RootResourceTypeReadOperationDisplayName
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeReadOperationDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Writes Root resources..
        /// </summary>
        internal static string RootResourceTypeWriteOperationDescription
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeWriteOperationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Write Root Resource.
        /// </summary>
        internal static string RootResourceTypeWriteOperationDisplayName
        {
            get
            {
                return ResourceManager.GetString("RootResourceTypeWriteOperationDisplayName", resourceCulture);
            }
        }
    }
}
