/**
* @file Source code generated by PDL compiler.
* @version 1.0
* @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
* @schemaversion 1.0.0.2
*/
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-bundling root="true" />
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
define(["require", "exports", "Fx/Composition/Selectable"], function (require, exports, FxSelectable2) {
    "use strict";
    var BladeDefinitions;
    (function (BladeDefinitions) {
        var extensionName = "Microsoft_Azure_AD";
        function createOptions(onClosed, parameters, callbacks) {
            return {
                onClosed: onClosed,
                parameters: parameters,
                callbacks: callbacks
            };
        }
        var SelectMemberReference = (function (_super) {
            __extends(SelectMemberReference, _super);
            function SelectMemberReference(parameters, callbacks, onClosed) {
                _super.call(this, "SelectMember", extensionName, createOptions(onClosed, parameters, callbacks), {
                    outputParameters: [
                        "stepOutput"
                    ]
                });
            }
            return SelectMemberReference;
        }(FxSelectable2.PdlBladeReference));
        BladeDefinitions.SelectMemberReference = SelectMemberReference;
        var SelectMemberV3Reference = (function (_super) {
            __extends(SelectMemberV3Reference, _super);
            function SelectMemberV3Reference(options) {
                _super.call(this, "SelectMemberV3", extensionName, options);
            }
            return SelectMemberV3Reference;
        }(FxSelectable2.ParameterProviderBladeReference));
        BladeDefinitions.SelectMemberV3Reference = SelectMemberV3Reference;
        var RolesListBladeReference = (function (_super) {
            __extends(RolesListBladeReference, _super);
            function RolesListBladeReference(parameters, onClosed) {
                _super.call(this, "RolesListBlade", extensionName, createOptions(onClosed, parameters), {});
            }
            return RolesListBladeReference;
        }(FxSelectable2.PdlBladeReference));
        BladeDefinitions.RolesListBladeReference = RolesListBladeReference;
        var UserAssignmentsBladeReference = (function (_super) {
            __extends(UserAssignmentsBladeReference, _super);
            function UserAssignmentsBladeReference(parameters, onClosed) {
                _super.call(this, "UserAssignmentsBlade", extensionName, createOptions(onClosed, parameters), {});
            }
            return UserAssignmentsBladeReference;
        }(FxSelectable2.PdlBladeReference));
        BladeDefinitions.UserAssignmentsBladeReference = UserAssignmentsBladeReference;
    })(BladeDefinitions || (BladeDefinitions = {}));
    return BladeDefinitions;
});
