/**
* @file Source code generated by PDL compiler.
* @version 1.0
* @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
* @schemaversion 1.0.0.2
*/
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Resource/Create/ViewModels/CreateBladeViewModel" />
define(["require", "exports", "../../Resource/Create/ViewModels/CreateBladeViewModel"], function (require, exports) {
    "use strict";
    var Main;
    (function (Main) {
        "use strict";
        Main.blade = {
            "name": "CreateBlade",
            "viewModelName": "Resource$CreateBladeViewModel",
            "lenses": [],
            "width": 0,
            "style": 3,
            "actionBar": {
                "name": "",
                "actionBarKind": 1,
                "bindings": []
            },
            "templateBlade": {
                "htmlTemplate": null,
                "parameterProvider": true,
                "partSize": 0,
                "htmlTemplateInline": {
                    "file": "Create.html",
                    "content": "<div class=\"msportalfx-form\" data-bind=\"formElement: generalSection\"></div>"
                },
                "styleSheets": []
            },
            "attributes": 0
        };
    })(Main || (Main = {}));
    return Main;
});
