/**
* @file Source code generated by PDL compiler.
* @version 1.0
* @sdkversion 5.0.302.607 (production_sdk#ffbfc5d.170130-1133)
* @schemaversion 1.0.0.2
*/
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Resource/Properties/ViewModels/PropertiesBladeViewModel" />
/// <amd-dependency path="../../Resource/Properties/ViewModels/PropertiesPartViewModel" />
define(["require", "exports", "../../Resource/Properties/ViewModels/PropertiesBladeViewModel", "../../Resource/Properties/ViewModels/PropertiesPartViewModel"], function (require, exports) {
    "use strict";
    var Main;
    (function (Main) {
        "use strict";
        Main.blade = {
            "name": "PropertiesBlade",
            "inputs": [
                "id"
            ],
            "viewModelName": "Resource$PropertiesBladeViewModel",
            "lenses": [
                {
                    "name": "PropertiesBlade_lens1",
                    "partInstances": [
                        {
                            "name": "PropertiesPart",
                            "inline": {
                                "viewModel": "Resource$PropertiesPartViewModel",
                                "partKind": 24,
                                "inputs": [
                                    "id"
                                ],
                                "bindings": [
                                    {
                                        "property": "id",
                                        "valuesFrom": [
                                            {
                                                "referenceType": 1,
                                                "property": "id"
                                            }
                                        ]
                                    }
                                ],
                                "details": [
                                    {
                                        "invocationInputArguments": [
                                            {
                                                "valuesFrom": [
                                                    {
                                                        "referenceType": 0,
                                                        "property": "content.selection"
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        "invocationInputArguments": [
                                            {
                                                "valuesFrom": [
                                                    {
                                                        "referenceType": 0,
                                                        "property": "content.moveResourceSelection"
                                                    }
                                                ]
                                            }
                                        ],
                                        "outputArguments": [
                                            {
                                                "property": "actionBarOutput",
                                                "valuesFrom": [
                                                    {
                                                        "referenceType": 1,
                                                        "property": "actionBarOutput"
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ],
                                "initialSize": 8
                            }
                        }
                    ]
                }
            ],
            "viewModelInputs": [
                {
                    "property": "id",
                    "valuesFrom": [
                        {
                            "referenceType": 1,
                            "property": "id"
                        }
                    ]
                }
            ],
            "width": 0,
            "locked": true,
            "style": 6,
            "attributes": 0
        };
    })(Main || (Main = {}));
    return Main;
});
